### PR TITLE
Add Google Calendar integration for scheduled events

### PR DESCRIPTION
**Pull request by ladybunne**
### Overview

Hello! This one has been in the works for a bit, but here it is - a working implementation of Google Calendar support for AginahBot.

The way it works is that it mirrors `/schedule` commands onto a public, read-only Google Calendar. This calendar must be created via an opt-in command, `/schedule-calendar`, after which any future `/schedule` commands will start to populate the calendar. Calendars are **per-guild**, and the integration is designed in such a way that it won't interfere with normal usage even if the calendar isn't enabled.

To set this up and test it, `config.json` needs to have these two fields. It will fail without them.
```
"google_api_client_email": your-client-email-here
"google_api_private_key": your-private-key-here
```

It's fairly straightforward to get credentials from Google - I can provide guidance if it's needed.

Two columns have also been added to the database, to facilitate this feature:
- `gCalendarId`, a varchar(128), to `guild_data`, which represents a Google Calendar's unique ID
- `gEventId`, a varchar(128), to `scheduled_events`, which represents a Google Calendar event's unique ID

### Current features

- [x] Authentication via the Google Calendar API
- [x] Creation of deletion of per-guild calendars, including database storage
- [x] Creation, rescheduling and deletion of events within the calendar, including database storage

### Future features

- [ ] Colour-coding of events based on role pings
- [ ] A link to the calendar at the top of schedule boards
- [ ] Individual Google Calendar event links on each event embed
- [ ] Proper error handling for cases where sufficient Google Calendar API credentials aren't provided

### Closing Thoughts

I'm eagerly looking for feedback on this, so feel free to ask questions, add comments and the like! Nothing is set in stone, and I expect a lot of this to change based on style, security and convention reasons.

(As a note: vanilla JavaScript is a bit tricky for me, so please bear with me.)

Thank you! Hopefully this can be useful to the project!

### CODE REVIEW

**Comment by ladybunne** [comment]
Closing this as it seems like there's no interest in the feature at this time, unfortunately. If that changes I'm happy to reopen it.

**Comment by LegendaryLinux** [comment]
I fixed the merge conflict. Would you prefer I push to this branch, or make a new one and PR into your branch?

**Comment by LegendaryLinux** [comment]
I've opened a PR against your fork: https://github.com/ladybunne/AginahBot/pull/1

**Comment by ladybunne** [comment]
I wanted to ask - since this has been merged (yay!), is it likely this feature will be enabled for the main AP server, or are there prohibitive factors stopping that from happening?

**Comment by LegendaryLinux** [comment]
It will eventually happen, but I want to fix the depreciation warnings and probably replace the Google Calendar API package.

**Pull request merged**
